OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "sk-IrIgzFee3yL0i2ccD5Bb6820566843EcBcDd1b94B034D01a"
  base_url: "https://api.xiaoai.plus/v1"

GLMModel:
  model_url: "your_chatglm_model_url"
  timeout: 300

common:
  book: "tests/test.pdf"
  file_format: "markdown"